- name: Set zookeeper connection string
  set_fact:
    zk_connect: "{% for node in kafka_zookeeper %}{{ node.host }}:{{ node.port }}{% if not loop.last %},{% endif %}{% endfor %}"
- name: Set kafka base path
  set_fact:
    base_path: "{{ apache_kafka_home }}/kafka_2.12-{{ apache_kafka_version }}"


#command: "{{ base_path }}/bin/kafka-topics.sh --bootstrap-server {{ inventory_hostname }}:9093 --command-config {{ base_path }}/config/client-config.properties --list"
- name: List currently installed topics
  command: >
    {{ base_path }}/bin/kafka-topics.sh 
    --bootstrap-server {{ inventory_hostname }}:9093 
    --command-config {{ base_path }}/config/client-config.properties 
    --list
  register: list_topics

- name: Create topics not existing
  command: "{{ base_path }}/bin/kafka-topics.sh --create --bootstrap-server {{ inventory_hostname }}:9093 --command-config {{ base_path }}/config/client-config.properties --topic {{ item.topic }}"
  with_items:
    - "{{ topic_configuration }}"
  when: item.topic not in list_topics.stdout_lines


#
#topic_configuration:
#  - { topic: "topic1", acl_list: [
#   { operation: "read", principal: "bob" }
#      ]
#    }
#


# spacing in " {{ topic.... will kill you below!
- name: Create ACL for write operation
  #https://stackoverflow.com/questions/31566568/double-loop-ansible
  command: >
    {{ base_path }}/bin/kafka-acls.sh --add 
    --bootstrap-server {{ inventory_hostname }}:9093 
    --command-config {{ base_path }}/config/client-config.properties 
    --allow-principal User:{{ item.1.principal }} 
    --producer 
    --transactional-id '*' 
    --topic {{ item.0.topic }} 
    --idempotent
  with_subelements: [ "{{ topic_configuration }}", "acl_list" ]
  when: item.1.operation == "write"


- name: Create ACL for read operation
  #https://stackoverflow.com/questions/31566568/double-loop-ansible
  command: >
    {{ base_path }}/bin/kafka-acls.sh --add 
    --bootstrap-server {{ inventory_hostname }}:9093 
    --command-config {{ base_path }}/config/client-config.properties 
    --allow-principal User:{{ item.1.principal }} 
    --consumer
    --group '*' 
    --topic {{ item.0.topic }} 
  with_subelements: [ "{{ topic_configuration }}", "acl_list" ]
  when: item.1.operation == "write"
