- name: Set zookeeper connection string
  set_fact:
    zk_connect: "{% for node in kafka_zookeeper %}{{ node.host }}:{{ node.port }}{% if not loop.last %},{% endif %}{% endfor %}"
- name: Set kafka base path
  set_fact:
    base_path: "{{ apache_kafka_home }}/kafka_2.12-{{ apache_kafka_version }}"


#--command-config
- name: List currently installed topics
  command: "{{ base_path }}/bin/kafka-topics.sh --bootstrap-server {{ inventory_hostname }}:9093 --command-config {{ base_path }}/config/client-config.properties --list"
  register: list_topics

- name: Create topics not existing
  command: "{{ base_path }}/bin/kafka-topics.sh --create --bootstrap-server {{ inventory_hostname }}:9093 --command-config {{ base_path }}/config/client-config.properties --topic {{ item.topic }}"
  with_items:
    - "{{ topic_configuration }}"
  when: item.topic not in list_topics.stdout_lines

