# Each node may be configured to run a number of different personalities (namenode, jounalnode,etc).
# If applicable this attempts to operate on all of them


- name: Include journalnode
  include_tasks:
    file: journalnode_service.yml

- name: Include namenode
  include_tasks:
    file: namenode_service.yml

- name: Include datanode
  include_tasks:
    file: datanode_service.yml





