#HAUtil wants two nodes even if one doesn't exist to format
namenodes:
- { shortname: "fedora" , host: "fedora" }
- { shortname: "other" , host: "other" }
journalnodes:
- { host: "fedora", port: 8485 }
zookeeper:
- { host: "fedora", port: 2182 }
hadoop_hostvar_topology:
- { host: "fedora" }
