#HAUtil wants two nodes even if one doesn't exist to format
namenodes:
- { shortname: "fedora" , host: "fedora" }
- { shortname: "other" , host: "other" }
journalnodes:
- { host: "fedora", port: 8485 }
zookeeper:
- { host: "fedora", port: 2182 }






  ## {% if secure_zookeeper_hadoop_env.enable == true %}
  ##HADOOP_OPTS="${HADOOP_OPTS} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty "
  ##HADOOP_OPTS="${HADOOP_OPTS} -Dzookeeper.ssl.keyStore.location={{ secure_zookeeper_hadoop_env.keystore_location }}"
  ##HADOOP_OPTS="${HADOOP_OPTS} -Dzookeeper.ssl.keyStore.password={{ secure_zookeeper_hadoop_env.keystore_password }}"
  ##HADOOP_OPTS="${HADOOP_OPTS} -Dzookeeper.ssl.trustStore.location={{ secure_zookeeper_hadoop_env.truststore_location }}"
  ##HADOOP_OPTS="${HADOOP_OPTS} -Dzookeeper.ssl.trustStore.password={{ secure_zookeeper_hadoop_env.truststore_password }}"
  ##HADOOP_OPTS="${HADOOP_OPTS} -Dzookeeper.ssl.hostnameVerification={{ secure_zookeeper_hadoop_env.hostname_verification }}"
  ##{% endif %}