kafka_brokers:
- "fedora"

kafka_data_dir: /home/edgy/edgy-kafka/var

kafka_zookeeper:
  - { host: "fedora", port: 2182 }

topic_configuration:
  - { topic: "topic1", acl_list: [
        { operation: "read", principal: "bob" },
        { operation: "write", principal: "bob" }
      ] }