- name: Create ca
  hosts: 127.0.0.1
  connection: local

  vars:
    CA_PASS_YOU_SET: "itssecret"
    CA_SUB: "/C=US/ST=New York/L=New York/O=arizone cert/OU=arizona unit/CN=teknek.io"
  tasks:
    - name: stat ca
      stat: 
        path: myCA.key
      register: ca_stat

    - name: generate ca
      shell: "openssl genrsa -des3 -out myCA.key -passout pass:{{ CA_PASS_YOU_SET }} 2048"
      when: not ca_stat.stat.exists

    - name: stat root
      stat:
        path: myCA.pem
      register: pem_stat

      ## todo requires interactive password
    - name: root ca
      shell: "openssl req -x509 -new -nodes -key myCA.key -sha256 -days 1825 -out myCA.pem  -subj \"{{ CA_SUB }}\" "
      when: not pem_stat.stat.exists

    - name: display pem
      shell: "openssl x509 -in myCA.pem -noout -text"
      register: pem_out
      when: not pem_stat.stat.exists

    - name: make crt
      shell: "openssl x509 -outform der -in myCA.pem -out myCA.crt"
 
    - name: debug pem 
      debug:
        var: pem_out
