apache_hadoop_home: /home/edgy/arizona-storage-compute
#Consider renaming this variable to fs.defaultFS 
dfs_clustername: fs_abc

apache_zookeeper_home: /home/edgy/arizona-keeper

keystore_location: fedora.jks
keystore_password: ssshhh

truststore_location: myTruststore.jks
truststore_password: itssecret