#edgy-simple-local-ca
edgy_simple_file_root: /home/edward/edgy-ansible/roles/edgy-simple-ca/files
CA_PASS_YOU_SET: "itssecret"
CA_SUB: "/C=US/ST=New York/L=New York/O=arizone cert/OU=arizona unit/CN=teknek.io"
#This should not be the same password as the CRT as it only protects "shareable" information of the truststore
CA_TRUSTSTORE_PASSWORD: "itssecret"

CLIENT_FQDN: fedora
CLIENT_PASS_YOU_SET: "ssshhh"
CLIENT_SUB: "/C=US/ST=New York/L=New York/O=arizone cert/OU=arizona unit/CN={{ CLIENT_FQDN }}"




apache_zookeeper_home: /home/edgy/arizona-keeper
zk_id: 1

keystore_location: "fedora.jks"
keystore_password: "ssshhh"

truststore_location: "myTruststore.jks"
truststore_password: "itssecret"


apache_hadoop_home: /home/edgy/arizona-storage-compute

#///usr/lib/jvm/temurin-17-jdk
hadoop_env_append:
  - "export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk"
# Controls the system use that can run the namenode
  - "export HDFS_NAMENODE_USER=edgy"

journalnode_personality: True
namenode_personality: True
datanode_personality: True
resourcemanager_personality: True

secure_zookeeper_hadoop_env:
  enable: true
hadoop_zookeeper_keystore_location: fedora.jks
hadoop_zookeeper_keystore_password: ssshhh
hadoop_zookeeper_truststore_location: "myTruststore.jks"
hadoop_zookeeper_truststore_password: "itssecret"
hadoop_zookeeper_hostname_verification: "false"

hadoop_heapsize_max: 200M

hadoop_rack: "/availability-zone-1"

### start: edgy-spark ###
edgy_spark_home: /home/edgy/edgy_spark
spark_env_append:
  - "export JAVA_HOME=/usr/lib/jvm/temurin-8-jdk"
  - "export SPARK_DIST_CLASSPATH=$({{ apache_hadoop_home }}/hadoop-3.4.1/bin/hadoop classpath)"
  - "export HADOOP_CONF_DIR={{ apache_hadoop_home }}/hadoop-3.4.1/etc/hadoop"
### end: edgy-spark ###

### start: edgy-kafka ###
apache_kafka_home: /home/edgy/edgy-kafka
kafka_broker_id: 100
kafka_rack: "/availability-zone-1"
kafka_keystore_location: fedora.jks
kafka_keystore_password: ssshhh
kafka_server_cn: "CN=fedora"
kafka_truststore_location: "myTruststore.jks"
kafka_truststore_password: "itssecret"
### end: edgy-kafka